version: "3.8"

services:
    postgres:
        image: postgres:15
        environment:
            POSTGRES_DB: library
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - laravel_network

volumes:
    postgres_data:

networks:
    laravel_network:
        driver: bridge
